ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
  hosts:
    - jhamaltheademo.dev.renku.ch
  tls:
    - hosts:
      - jhamaltheademo.dev.renku.ch
      secretName: jhamaltheademo-ch-tls

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false

proxy:
  service:
    type: ClusterIP

hub:
  services:
    amalthea:
      url: https://jhamaltheademo.dev.renku.ch/services/amalthea/patch
      oauth_redirect_uri: "https://jhamaltheademo.dev.renku.ch/services/amalthea/patch/oauth2/callback"
      oauth_client_id: amalthea
  config:
    Authenticator:
      admin_users:
        - user1
        - user2
      allowed_users:
        - user3
        - user4
    DummyAuthenticator:
      password: "test123456"
    JupyterHub:
      authenticator_class: dummy
