apiVersion: amalthea.dev/v1alpha1
kind: JupyterServer
metadata:
  name: test-patch-example
  namespace: jhamaltheademo
spec:
  auth:
    oidc:
      enabled: true
      clientId: test
      clientSecret:
        value: test
      issuerUrl: test
  routing:
    host: jhamaltheademo.dev.renku.ch
    path: /services/amalthea/patch
    ingressAnnotations:
      kubernetes.io/ingress.class: nginx
    tls: 
      enabled: true
      secretName: jhamaltheademo-ch-tls
  patches:
    - type: "application/json-patch+json"
      patch:
        - op: remove
          path: /statefulset/spec/template/spec/containers/0/readinessProbe
        - op: remove
          path: /statefulset/spec/template/spec/containers/0/startupProbe
        - op: remove
          path: /statefulset/spec/template/spec/containers/0/livenessProbe
        - op: remove
          path: /statefulset/spec/template/spec/containers/1/env
        - op: replace
          path: "/statefulset/spec/template/spec/containers/1/args"
          value: 
            - --provider=oidc
            - --client-id=amalthea
            - --client-secret=""
            - --login-url=https://jhamaltheademo.dev.renku.ch/hub/api/oauth2/authorize
            - --redeem-url=https://jhamaltheademo.dev.renku.ch/hub/api/oauth2/token
            - --session-cookie-minimal
            - --http-address=:4180
            - --skip-provider-button
            - --upstream=http://127.0.0.1:8888
            - --redirect-url=https://jhamaltheademo.dev.renku.ch/services/amalthea/patch/oauth2/callback
            - --cookie-path=/services/amalthea/patch
            - --proxy-prefix=/services/amalthea/patch/oauth2
            - --skip-auth-route=^/services/amalthea/patch/api/status$
            - --email-domain=*
            - --cookie-secret=1ebZsOvnouItYixdnoEgBIaYl97LAwgarm23nm8wDZQ=
            - --insecure-oidc-allow-unverified-email=true
            - --cookie-domain=jhamaltheademo.dev.renku.ch
            - --verbose=true
